### ISSUE TITLE
pytz模块以及微信/QQ通知

### ISSUE THREAD

**Issue by yinghope** [HowardZorn/hfut_auto_check-in#1]
第一次执行时发现缺少pytz模块，应该需要在requirement中添加；
可以添加微信/QQ通知功能，定时执行可以收到执行结果信息：
微信通知：[http://sc.ftqq.com/3.version](url)
QQ通知：[https://qmsg.zendee.cn/index.html](url)

**Comment by HowardZorn** [comment]
> 第一次执行时发现缺少pytz模块，应该需要在requirement中添加；

确实如此

> 可以添加微信/QQ通知功能

这个可以自己做集成。目前 Server 酱需要申请企业微信，挺麻烦的。一位 fork 的同学（ @luobolong）有做邮件通知，我其实一开始就有做，只不过没有上传罢了。其实我还可以把 GitHub Action 脚本给写了。不过我认为这些其实是用户的事情，所以只打算提供接口的功能。

感谢关注我的项目，欢迎 fork/PR 加上自己想要的功能

**Comment by HowardZorn** [comment]
目前已经改正`requirements.txt`中的问题。
